version: 2.1

commands:
  bundle_install:
    description: 'Perform bundler installation, relying on CircleCI cache for performance'
    steps:
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Bundle install'
          command: |
            set -euxo pipefail
            bundle config set frozen 'true'
            bundle install --path=.bundle
      - save_cache:
          key: bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle
  yarn_install:
    description: 'Perform node module installation, relying on CircleCI cache for performance'
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: 'Yarn install'
          command: bin/yarn install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  run_rubocop:
    description: 'Run rubocop'
    steps:
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Run rubocop'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rubocop
  rspec_backend:
    description: 'Run rspec backend specs'
    steps:
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: 'Run rspec backend specs'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rails db:create
            bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/rspec_backend/rspec.xml
  mocha_specs:
    description: 'Run mocha specs'
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: 'Run mocha specs'
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: /tmp/frontend/test-results.xml
  rspec_system:
    description: 'Run rspec system specs'
    steps:
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: 'Run rspec system specs'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rails db:create
            bundle exec rails webpacker:compile
            bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/rspec_system/rspec.xml spec/system

app_image: &app_image
  image: circleci/ruby:2.7.2-node-browsers
db_image: &db_image
  image: circleci/postgres:latest

jobs:
  bundle:
    docker:
      - <<: *app_image
    steps:
      - checkout
      - bundle_install
  yarn:
    docker:
      - <<: *app_image
    steps:
      - checkout
      - yarn_install
  rubocop:
    docker:
      - <<: *app_image
    steps:
      - checkout
      - run_rubocop
  backend_specs:
    docker:
      - <<: *app_image
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - <<: *db_image
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: mutualaid_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - rspec_backend
      - store_test_results:
          path: /tmp/rspec_backend
  frontend_specs:
    docker:
      - <<: *app_image
    steps:
      - checkout
      - mocha_specs
      - store_test_results:
          path: /tmp/frontend
      - store_artifacts:
          path: /tmp/frontend
  system_specs:
    docker:
      - <<: *app_image
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
          HEADLESS_CHROME: true
      - <<: *db_image
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: mutualaid_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - rspec_system
      - store_test_results:
          path: /tmp/rspec_system

workflows:
  version: 2.1
  mutual_aid:
    jobs:
      - bundle
      - yarn
      - rubocop:
          requires:
            - bundle
      - backend_specs:
          requires:
            - bundle
            - yarn
      - frontend_specs:
          requires:
            - yarn
      - system_specs:
          requires:
            - bundle
            - yarn
